  name: Checkout
  on: [push]
  
  
  jobs:
    test:
      name: Run tests
      runs-on: ubuntu-latest
      env:
        run_this_workflow: true  # Aseta ympäristömuuttuja tähän
      if: ${{ env.run_this_workflow == 'true' }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.7
        - name: Run tests
          run: |
            echo "Running tests"
            echo "Tests passed ${{ github.run_number }}"
            echo "Current date and time: $(TZ='Europe/Helsinki' date +%Y-%m-%d\ %H:%M:%S)"
            echo "Triggered by: ${{ github.event_name }}"

