  name: Remote Sync with Manual Trigger
  on: [workflow_dispatch]
  
  jobs:
    Sync:
      name: Chechout
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.7
        - name: rsync
          uses: burnett01/rsync-deployments@7.0.1
          with:
            switches: -avzr --delete
            legacy_allow_rsa_hostkeys: "true"
            path: /home/vesa-matti/Projektit/actions-rsync-test/
            remote_path: /home/vmuser/rsync/
            remote_host: 10.67.220.191
            remote_user: vmuser
            remote_key: ${{ secrets.REMOTE_KEY }}
            remote_key_pass: ${{ secrets.REMOTE_KEY_PASS }}

